-- MySQL Workbench Synchronization
-- Generated: 2023-04-26 08:18
-- Model: New Model
-- Version: 1.0
-- Project: Name of the project
-- Author: Beto

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

CREATE SCHEMA IF NOT EXISTS `EVIDENCIA_3` DEFAULT CHARACTER SET utf8 ;

CREATE TABLE IF NOT EXISTS `EVIDENCIA_3`.`UNIDAD` (
  `id_unidad` SMALLINT(1) NOT NULL,
  `modelo` TINYTEXT NOT NULL,
  `placa` TINYTEXT NOT NULL,
  `activo` CHAR(1) NOT NULL,
  `CATEGORIA_id_categoria` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id_unidad`),
  INDEX `fk_UNIDAD_CATEGORIA1_idx` (`CATEGORIA_id_categoria` ASC) VISIBLE,
  CONSTRAINT `fk_UNIDAD_CATEGORIA1`
    FOREIGN KEY (`CATEGORIA_id_categoria`)
    REFERENCES `EVIDENCIA_3`.`CATEGORIA` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `EVIDENCIA_3`.`CATEGORIA` (
  `id_categoria` TINYINT(1) NOT NULL,
  `nombre_categoria` TINYTEXT NOT NULL,
  `capacidad_maxima` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `EVIDENCIA_3`.`OPERADOR` (
  `id_operador` SMALLINT(1) NOT NULL,
  `apellido` TINYTEXT NOT NULL,
  `nombre` TINYTEXT NOT NULL,
  `fecha_nacimiento` DATE NOT NULL,
  `fecha_ingreso` DATE NOT NULL,
  `nss` CHAR(9) NOT NULL,
  `activo` CHAR(1) NOT NULL,
  PRIMARY KEY (`id_operador`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `EVIDENCIA_3`.`LOCACION` (
  `id_locacion` SMALLINT(1) NOT NULL,
  `nombre` TINYTEXT NOT NULL,
  PRIMARY KEY (`id_locacion`),
  INDEX `id_locacion_idx` (`id_locacion` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `EVIDENCIA_3`.`TRAYECTO` (
  `id_trayecto` MEDIUMINT(1) NOT NULL,
  `id_unidad` SMALLINT(1) NOT NULL,
  `fecha_hora_salida` DATETIME NOT NULL,
  `fecha_hora_llegada` DATETIME NOT NULL,
  `id_locacion_salida` SMALLINT(1) NOT NULL,
  `id_locacion_destino` SMALLINT(1) NOT NULL,
  `id_operador` SMALLINT(1) NOT NULL,
  `id_asistente` SMALLINT(1) NOT NULL,
  `estatus_viaje` TINYTEXT NOT NULL,
  `boletos_vendidos` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id_trayecto`),
  INDEX `fk_TRAYECTO_LOCACION1_idx` (`id_locacion_destino` ASC) VISIBLE,
  INDEX `fk_TRAYECTO_UNIDAD1_idx` (`id_unidad` ASC) VISIBLE,
  INDEX `fk_TRAYECTO_OPERADOR1_idx` (`id_operador` ASC) VISIBLE,
  INDEX `fk_TRAYECTO_OPERADOR2_idx` (`id_asistente` ASC) VISIBLE,
  INDEX `fk_TRAYECTO_LOCACION2_idx` (`id_locacion_salida` ASC) VISIBLE,
  CONSTRAINT `fk_TRAYECTO_LOCACION1`
    FOREIGN KEY (`id_locacion_destino`)
    REFERENCES `EVIDENCIA_3`.`LOCACION` (`id_locacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TRAYECTO_UNIDAD1`
    FOREIGN KEY (`id_unidad`)
    REFERENCES `EVIDENCIA_3`.`UNIDAD` (`id_unidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TRAYECTO_OPERADOR1`
    FOREIGN KEY (`id_operador`)
    REFERENCES `EVIDENCIA_3`.`OPERADOR` (`id_operador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TRAYECTO_OPERADOR2`
    FOREIGN KEY (`id_asistente`)
    REFERENCES `EVIDENCIA_3`.`OPERADOR` (`id_operador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TRAYECTO_LOCACION2`
    FOREIGN KEY (`id_locacion_salida`)
    REFERENCES `EVIDENCIA_3`.`LOCACION` (`id_locacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
